import { Buffer } from "buffer";
import MDBReader from "mdb-reader";
type Row=Record<string,unknown>;
const n=(v:unknown)=>typeof v==="number"?v:Number(v)||0;
const t=(v:unknown)=>v==null?null:String(v).trim()||null;
const d=(v:unknown)=>v instanceof Date?v.toISOString().slice(0,10):t(v);
const fixService=(v:unknown)=>{const x=String(v||"Serviço sem descrição").trim().replace(/\s+/g," "),f:Record<string,string>={"diferensa de férias":"Diferença de férias","fasendo mudas":"Fazendo mudas","fasendo aceiro":"Fazendo aceiro","disbrotando cacau":"Desbrotando cacau","cutivo de mamão":"Cultivo de mamão","conservaçao de estrada":"Conservação de estrada","demarcaçao":"Demarcação","folga de aviso previo":"Folga de aviso prévio","salário familia":"Salário-família","combate à pragas":"Combate a pragas"};return f[x.toLocaleLowerCase("pt-BR")]||x};
export async function parseAccessInBrowser(file:File,password:string){
 const reader=new MDBReader(Buffer.from(await file.arrayBuffer()),{password}),names=reader.getTableNames({normalTables:true,systemTables:false,linkedTables:true});
 const get=(name:string)=>names.includes(name)?reader.getTable(name).getData() as Row[]:[];
 const companies=get("TB_Empresas").map(r=>{const doc=t(r.CNPJ_CEI),digits=String(doc||"").replace(/\D/g,"");return{sourceId:n(r.CodDaEmpresa),name:t(r.NomeDaEmpresa)||"Empresa sem nome",document:digits.length===12?null:doc,documentType:digits.length===12?"caepf":"cnpj",cei:digits.length===12?digits:null,city:t(r.Cidade),state:t(r.UF),address:t(r.Endereco),district:t(r.Bairro),postalCode:t(r.CEP),phone:t(r.Telefone),email:t(r.Email)}});
 const contracts=get("TB_Cadastro_Pessoal").map(r=>({sourceRegistration:n(r.Matricula),companySourceId:n(r.CodDaEmpresa),name:t(r.Nome)||"Colaborador sem nome",cpf:t(r.CPF),pis:t(r.PIS),birthDate:d(r.Nascimento),birthCity:t(r.Naturalidade),birthState:t(r.UF_Naturalidade),address:t(r.Endereco),district:t(r.Bairro),city:t(r.Cidade),state:t(r.UF_Cidade),postalCode:t(r.CEP),identityNumber:t(r.Identidade),identityIssuer:t(r.Orgao),identityState:t(r.UF_orgao),identityIssueDate:d(r.Emissao),voterTitleNumber:t(r.Titulo),voterZone:t(r.Zona),voterSection:t(r.Secao),ctpsNumber:t(r.CTPS),ctpsIssueDate:d(r.Emissao_CTPS),phone:t(r.Telefone),admissionDate:d(r["Admissão"]),terminationDate:d(r.Data_rescisao),role:t(r.Funcao),active:r.Ativo===true&&!r.Data_rescisao}));
 const groups=new Map(get("TB_Grupo").map(r=>[n(r.CodigoDoGrupo),t(r.Grupo)])),units=new Map(get("TB_Unidade de Apontamento").map(r=>[n(r.CodUnidade),t(r.Unidade)]));
 const services=get("TB_Cadastro de Servicos").map(r=>{const g=n(r.CodigoDoGrupo),u=n(r.CodUnidade);return{sourceId:n(r.CodServico),groupSourceId:g,description:fixService(r.Descricao),unitSourceId:u,fgts:Boolean(r.FGTS),fgts13:Boolean(r["FGTS 13 Sal"]),inss:Boolean(r.INSS),inss13:Boolean(r["INSS 13"]),rais:Boolean(r.RAIS),formulaCode:t(r.Formula),groupName:groups.get(g)||null,unitName:units.get(u)||null,affectsDsr:g>=4,active:true}});
 const dep=get("TB_Dependente").map(r=>({sourceId:n(r.Cad_Dep),companySourceId:n(r.CodEmpresa)||1,sourceRegistration:n(r.Matricula),name:t(r.Dependente),birthDate:d(r.Nascimento),dependentType:"other",cpf:null})).filter(r=>r.name);
 const inventory={categories:get("TB_Grupo_Insumos").map(r=>({sourceId:n(r.CodGrupo),name:t(r.Grupo)||"Sem categoria"})),suppliers:get("TB_Fornecedor").map(r=>({sourceId:n(r.CodFornecedor),name:t(r.Fornecedor)||"Fornecedor sem nome",tradeName:t(r.Fantasia),phone:t(r.Fone),contactName:t(r.Contato)})),products:get("TB_Produtos").map(r=>({sourceId:n(r.CodProduto),categorySourceId:n(r.CodGrupo),description:t(r.Descricao)||"Produto sem descrição",unit:t(r.Unidade)||"UN"})),purchases:get("TB_Entrada1").map(r=>({sourceId:n(r.CodEntrada),companySourceId:n(r.CodEmpresa),supplierSourceId:n(r.CodFornecedor),date:d(r.Data),documentNumber:t(r.NotaCupom)})),purchaseItems:get("TB_Detalhes Entrada1").map(r=>({purchaseSourceId:n(r.CodEntrada),productSourceId:n(r.CodProduto),quantity:n(r.Quantidade),totalValue:n(r.Valor),notes:t(r["Observação"])}))};
 const headers=get("TB_Lançamentos"),details=get("TB_Detalhes do Lançamento"),headerMap=new Map(headers.map(r=>[n(r.Sequencia),{company:n(r.CodDaEmpresa),registration:n(r.Matricula),date:d(r.Competencia)}]));
 const historyEntries=details.map(r=>{const h=headerMap.get(n(r.Sequencia)),quantity=n(r.Producao),amount=Math.round(n(r.Valor)*100);if(!h||!d(r.Data))return null;return{companySourceId:h.company,entryDate:d(r.Data),sourceRegistration:h.registration,serviceSourceId:n(r.CodServico),quantity,unitPriceCents:quantity?Math.round(amount/quantity):0,amountCents:amount,discountCents:Math.round(n(r.Desconto)*100),sourceSequence:n(r.Sequencia)}}).filter(Boolean);
 return{fileName:file.name,companies,contracts,services,dependents:dep,inventory,peopleCount:new Set(contracts.map(r=>String(r.cpf||`${r.companySourceId}:${r.sourceRegistration}`))).size,activeCount:contracts.filter(r=>r.active).length,dependentsCount:dep.length,detailsCount:details.length,launchesCount:headers.length,historyEntries};
}
