"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from "react";
import "./inventory.css";
type AnyRow = Record<string, any>;
const brl = (c:number) => new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format((c||0)/100);
export default function InventoryModule({ company }:{ company:string }) {
  const [data,setData]=useState<AnyRow>({products:[],partners:[],movements:[],metrics:{}}), [tab,setTab]=useState("dashboard"), [message,setMessage]=useState("");
  const load=()=>fetch(`/api/inventory?company=${company}`,{cache:"no-store"}).then(r=>r.json()).then(b=>{setData(b);setMessage(b.error||"")});
  // A troca de empresa deve sempre descartar o estoque anterior.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{ void load(); },[company]);
  const suppliers=useMemo(()=>data.partners?.filter((p:AnyRow)=>p.partner_type!=="customer")||[],[data]);
  async function submit(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();const f=new FormData(e.currentTarget),body=Object.fromEntries(f);const r=await fetch("/api/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,action,company})});const b=await r.json();setMessage(b.message||b.error);if(r.ok){e.currentTarget.reset();load();}}
  return <section className="module inventory-module">
    <div className="module-hero inventory-hero"><span>▦</span><div><small>GESTÃO AGRÍCOLA INTEGRADA</small><h2>Estoque, custos e receitas</h2><p>Controle simples de insumos, compras, consumo por cultura, vendas e rentabilidade.</p></div></div>
    <div className="inventory-tabs">{[["dashboard","Painel"],["products","Produtos"],["partners","Clientes e fornecedores"],["movements","Movimentações"],["reports","Relatórios"]].map(x=><button className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</div>
    {message&&<div className="inline-notice">{message}</div>}
    {tab==="dashboard"&&<><div className="inventory-kpis"><article><small>VALOR EM ESTOQUE</small><b>{brl(data.metrics?.inventoryValue)}</b></article><article><small>COMPRAS</small><b>{brl(data.metrics?.purchases)}</b></article><article><small>FATURAMENTO</small><b>{brl(data.metrics?.revenue)}</b></article><article className={data.metrics?.lowStock?"warning":""}><small>ESTOQUE BAIXO</small><b>{data.metrics?.lowStock||0}</b></article></div><h3>Itens que exigem atenção</h3><Table rows={(data.products||[]).filter((p:AnyRow)=>Number(p.stock)<=Number(p.minimum_stock))}/></>}
    {tab==="products"&&<div className="inventory-grid"><form onSubmit={e=>submit(e,"product")} className="inventory-form"><h3>Novo produto</h3><input name="description" placeholder="Descrição do produto" required/><input name="sku" placeholder="Código/SKU"/><select name="unit"><option>UN</option><option>KG</option><option>L</option><option>TON</option><option>SC</option><option>CX</option></select><input name="minimumStock" type="number" step="0.001" placeholder="Estoque mínimo"/><input name="salePrice" type="number" step="0.01" placeholder="Preço de venda"/><button className="primary">Salvar produto</button></form><Table rows={data.products||[]}/></div>}
    {tab==="partners"&&<div className="inventory-grid"><form onSubmit={e=>submit(e,"partner")} className="inventory-form"><h3>Novo cliente ou fornecedor</h3><select name="partnerType"><option value="supplier">Fornecedor</option><option value="customer">Cliente</option><option value="both">Cliente e fornecedor</option></select><input name="name" placeholder="Nome/Razão social" required/><input name="tradeName" placeholder="Nome fantasia"/><input name="document" placeholder="CPF/CNPJ"/><input name="phone" placeholder="Telefone"/><input name="email" type="email" placeholder="E-mail"/><button className="primary">Salvar cadastro</button></form><PartnerTable rows={data.partners||[]}/></div>}
    {tab==="movements"&&<div className="inventory-grid"><form onSubmit={e=>submit(e,"movement")} className="inventory-form"><h3>Nova movimentação</h3><select name="movementType"><option value="purchase">Compra/entrada</option><option value="consumption">Consumo na lavoura</option><option value="sale">Venda/receita</option><option value="positive_adjustment">Ajuste positivo</option><option value="negative_adjustment">Ajuste negativo</option></select><select name="productId" required><option value="">Selecione o produto</option>{(data.products||[]).map((p:AnyRow)=><option value={p.id} key={p.id}>{p.description}</option>)}</select><select name="partnerId"><option value="">Sem parceiro</option>{suppliers.map((p:AnyRow)=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input name="date" type="date" required/><input name="quantity" type="number" min="0.0001" step="0.0001" placeholder="Quantidade" required/><input name="unitValue" type="number" step="0.01" placeholder="Valor unitário"/><input name="crop" placeholder="Cultura (cana, cacau...)"/><input name="costCenter" placeholder="Talhão/centro de custo"/><input name="documentNumber" placeholder="Nota fiscal/documento"/><button className="primary">Registrar movimentação</button></form><MovementTable rows={data.movements||[]}/></div>}
    {tab==="reports"&&<><div className="report-callout"><h3>Visão gerencial</h3><p>Compras, consumo, faturamento e margem por produto, cultura e centro de custo. Use a impressão do navegador para gerar PDF.</p><button className="secondary" onClick={()=>window.print()}>Imprimir relatório</button></div><MovementTable rows={data.movements||[]}/></>}
  </section>;
}
function Table({rows}:{rows:AnyRow[]}){return <div className="table-scroll"><table className="data-table"><thead><tr><th>Produto</th><th>Unidade</th><th>Estoque</th><th>Custo médio</th><th>Mínimo</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.description}</b></td><td>{r.unit}</td><td>{Number(r.stock||0).toLocaleString("pt-BR")}</td><td>{brl(r.average_cost_cents)}</td><td>{r.minimum_stock}</td></tr>)}</tbody></table></div>}
function PartnerTable({rows}:{rows:AnyRow[]}){return <div className="table-scroll"><table className="data-table"><thead><tr><th>Nome</th><th>Tipo</th><th>Documento</th><th>Contato</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b><small>{r.trade_name}</small></td><td>{r.partner_type==="supplier"?"Fornecedor":r.partner_type==="customer"?"Cliente":"Ambos"}</td><td>{r.document||"—"}</td><td>{r.phone||r.email||"—"}</td></tr>)}</tbody></table></div>}
function MovementTable({rows}:{rows:AnyRow[]}){return <div className="table-scroll"><table className="data-table"><thead><tr><th>Data</th><th>Movimento</th><th>Produto</th><th>Quantidade</th><th>Valor</th><th>Cultura/Centro</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{String(r.movement_date).split("-").reverse().join("/")}</td><td>{r.movement_type}</td><td><b>{r.inventory_products?.description}</b></td><td>{r.quantity} {r.inventory_products?.unit}</td><td>{brl(Number(r.quantity)*Number(r.unit_value_cents))}</td><td>{[r.crop,r.cost_center].filter(Boolean).join(" · ")||"—"}</td></tr>)}</tbody></table></div>}
