"use client";
import { useEffect,useMemo,useState } from "react";
import "./hr.css";
import CurrencyInput from "./currency-input";
import { brazilToday } from "./br-date";
type Tab="functions"|"links"|"references"|"adjustments"|"centers"|"epi"|"tools";
const today=brazilToday, brl=(c:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format((c||0)/100);
const sectionTabs:Record<string,Tab>={"Funções":"functions","Vínculos":"links","Evolução salarial":"references","Reajuste salarial":"adjustments","Centros de custo":"centers","EPI":"epi","Ferramentas":"tools"};
export default function RegistrationsModule({activeSection="Funções"}:{activeSection?:string}){
 const [tab,setTab]=useState<Tab>("functions"),[data,setData]=useState<any>({functions:[],centers:[],references:[],items:[],issues:[],workers:[]}),[msg,setMsg]=useState(""),[saving,setSaving]=useState(false),[from,setFrom]=useState(""),[to,setTo]=useState("");
 const [fn,setFn]=useState<any>({cboCode:"",officialDescription:"",localDescription:"",active:true}),[link,setLink]=useState<any>({code:"",description:"",active:true}),[center,setCenter]=useState<any>({description:"",active:true}),[ref,setRef]=useState<any>({referenceType:"national",effectiveDate:today(),value:"",notes:""});
 const [item,setItem]=useState<any>({itemType:"epi",description:"",supplier:"",ca:"",active:true}),[issue,setIssue]=useState<any>({itemIds:[],contractIds:[],issueDate:today(),quantity:1,returnDueDate:"",notes:"",acknowledged:false}),[workerFilter,setWorkerFilter]=useState(""),[itemFilter,setItemFilter]=useState(""),[showIssueHistory,setShowIssueHistory]=useState(true),[adj,setAdj]=useState<any>({functionIds:[],effectiveDate:today(),mode:"percentage",value:"",reason:"",updateProfiles:true});
 const load=async()=>{const r=await fetch(`/api/hr?fresh=${Date.now()}`,{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error||"Falha ao atualizar os cadastros.");setData(b);return b};
 useEffect(()=>{void load().catch(e=>setMsg(e instanceof Error?e.message:"Falha ao carregar os cadastros."))},[]);
 useEffect(()=>{setTab(sectionTabs[activeSection]||"functions")},[activeSection]);
 const save=async(body:any)=>{if(saving)return false;setSaving(true);setMsg("Salvando…");const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),30000);try{const r=await fetch("/api/hr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:controller.signal}),text=await r.text();let b:any={};try{b=text?JSON.parse(text):{}}catch{throw new Error(`Resposta inválida do servidor (${r.status}).`)}if(!r.ok)throw new Error(b.error||`Não foi possível salvar (${r.status}).`);const success=b.message||"Registro salvo com sucesso.";setMsg(success);try{await load();setMsg(`${success} Lista atualizada.`)}catch{setMsg(`${success} Atualize a tela para recarregar a lista.`)}return true}catch(e){setMsg(e instanceof DOMException&&e.name==="AbortError"?"O salvamento demorou além do esperado. Verifique a conexão e tente novamente.":e instanceof Error?e.message:"Não foi possível salvar.");return false}finally{window.clearTimeout(timer);setSaving(false)}};
 const editFunction=(row:any)=>setFn({id:row.id,cboCode:row.cbo_code||"",officialDescription:row.official_description||"",localDescription:row.local_description||"",active:row.active!==false});
 const refs=useMemo(()=>data.references.filter((r:any)=>(!from||r.effective_date>=from)&&(!to||r.effective_date<=to)),[data,from,to]),items=data.items.filter((x:any)=>x.item_type===(tab==="tools"?"tool":"epi")),visibleWorkers=data.workers.filter((x:any)=>`${x.registration_number||""} ${x.name||""}`.toLowerCase().includes(workerFilter.toLowerCase())),visibleItems=items.filter((x:any)=>String(x.description||"").toLowerCase().includes(itemFilter.toLowerCase())),issueRows=(data.issues||[]).filter((x:any)=>items.some((item:any)=>String(item.id)===String(x.item_id)));
 const toggle=(key:"contractIds"|"itemIds",id:any)=>setIssue((current:any)=>({...current,[key]:current[key].map(String).includes(String(id))?current[key].filter((value:any)=>String(value)!==String(id)):[...current[key],id]}));
 const printIssues=()=>{document.body.classList.add("printing-issue-history");window.print();window.setTimeout(()=>document.body.classList.remove("printing-issue-history"),300)};
 return <section className="module registrations-module"><div className="module-hero"><span>▦</span><div><small>CADASTROS E HISTÓRICOS</small><h2>{activeSection}</h2><p>Estrutura central para folha, segurança, patrimônio e análise gerencial.</p></div></div>
 {msg&&<div className="inline-notice">{msg}</div>}
 {tab==="functions"&&<><h3>Funções cadastradas</h3><Table rows={data.functions} cols={[["cbo_code","CBO"],["official_description","Descrição oficial"],["local_description","Descrição interna"],["usage_count","Vínculos"]]} edit={editFunction} del={x=>save({action:"delete",entity:"function",id:x.id})}/><h3>Cadastrar ou editar função</h3><CboSearchFields value={fn} setValue={setFn}/><button className="primary" disabled={saving} onClick={()=>save({action:"saveFunction",...fn}).then(ok=>ok&&setFn({cboCode:"",officialDescription:"",localDescription:"",active:true}))}>{saving?"Salvando…":"Salvar função"}</button></>}
 {tab==="links"&&<><h3>Vínculos cadastrados</h3><Table rows={data.links||[]} cols={[["code","Código"],["description","Descrição"],["usage_count","Colaboradores"]]} edit={row=>setLink({id:row.id,code:row.code||"",description:row.description||"",active:row.active!==false})} del={x=>save({action:"delete",entity:"link",id:x.id})}/><h3>Cadastrar ou editar vínculo</h3><div className="form-grid"><label>Código<input value={link.code} onChange={e=>setLink({...link,code:e.target.value})}/></label><label className="wide">Descrição do vínculo<input value={link.description} onChange={e=>setLink({...link,description:e.target.value})}/></label></div><button className="primary" disabled={saving} onClick={()=>save({action:"saveLink",...link}).then(ok=>ok&&setLink({code:"",description:"",active:true}))}>{saving?"Salvando…":"Salvar vínculo"}</button></>}
 {tab==="references"&&<><div className="service-tabs"><button className={ref.referenceType==="national"?"active":""} onClick={()=>setRef({...ref,referenceType:"national"})}>Salário mínimo nacional</button><button className={ref.referenceType==="category"?"active":""} onClick={()=>setRef({...ref,referenceType:"category"})}>Salário da categoria</button></div><div className="form-grid"><label>Data do reajuste<input type="date" value={ref.effectiveDate} onChange={e=>setRef({...ref,effectiveDate:e.target.value})}/></label><label>Valor (R$)<CurrencyInput value={ref.value} onValueChange={value=>setRef({...ref,value})}/></label><label className="wide">Observação<input value={ref.notes} onChange={e=>setRef({...ref,notes:e.target.value})}/></label></div><button className="primary" onClick={()=>save({action:"saveReference",...ref})}>Registrar evolução</button><div className="form-grid history-filter"><label>Data inicial<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Data final<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><Table rows={refs.map((r:any)=>({...r,value:brl(r.value_cents),type:r.reference_type==="national"?"Nacional":"Categoria"}))} cols={[["effective_date","Data"],["type","Referência"],["value","Valor"],["notes","Observação"]]}/></>}
 {tab==="adjustments"&&<><div className="form-grid"><label className="wide">Funções contempladas<select multiple value={adj.functionIds.map(String)} onChange={e=>setAdj({...adj,functionIds:Array.from(e.target.selectedOptions,o=>o.value)})}>{data.functions.map((f:any)=><option key={f.id} value={f.id}>{f.cbo_code} · {f.local_description||f.official_description}</option>)}</select><small>Nenhuma seleção = todas as funções ativas.</small></label><label>Data do reajuste<input type="date" value={adj.effectiveDate} onChange={e=>setAdj({...adj,effectiveDate:e.target.value})}/></label><label>Forma<select value={adj.mode} onChange={e=>setAdj({...adj,mode:e.target.value})}><option value="percentage">Índice percentual</option><option value="value">Novo salário</option></select></label><label>{adj.mode==="percentage"?"Percentual (%)":"Novo salário (R$)"}{adj.mode==="percentage"?<input type="number" step=".01" value={adj.value} onChange={e=>setAdj({...adj,value:e.target.value})}/>:<CurrencyInput value={adj.value} onValueChange={value=>setAdj({...adj,value})}/>}</label><label className="wide">Motivo/observação<input value={adj.reason} onChange={e=>setAdj({...adj,reason:e.target.value})}/></label><label className="check-field"><input type="checkbox" checked={adj.updateProfiles} onChange={e=>setAdj({...adj,updateProfiles:e.target.checked})}/>Atualizar cadastro dos colaboradores após confirmação</label></div><button className="primary" onClick={()=>confirm("Confirma o reajuste e a atualização do histórico salarial?")&&save({action:"applyAdjustment",...adj})}>Visualizar e confirmar reajuste</button> <button className="danger" onClick={()=>confirm(`Desfazer reajustes de ${adj.effectiveDate}?`)&&save({action:"undoAdjustment",effectiveDate:adj.effectiveDate})}>Desfazer por data</button></>}
 {tab==="centers"&&<><div className="form-grid"><label className="wide">Descrição do centro de custo<input value={center.description} onChange={e=>setCenter({...center,description:e.target.value})}/></label></div><button className="primary" onClick={()=>save({action:"saveCenter",...center}).then(ok=>ok&&setCenter({description:"",active:true}))}>Salvar centro de custo</button><Table rows={data.centers} cols={[["description","Descrição"],["created_at","Criação"],["usage_count","Serviços vinculados"]]} edit={setCenter} del={x=>save({action:"delete",entity:"center",id:x.id})}/></>}
 {(tab==="epi"||tab==="tools")&&<>
  <div className="service-tabs"><button className="active">Cadastro</button><button onClick={()=>document.getElementById("issue-form")?.scrollIntoView({behavior:"smooth"})}>Fornecimento em lote</button></div>
  <div className="form-grid"><label className="wide">Descrição da {tab==="epi"?"EPI":"ferramenta"}<input value={item.itemType===(tab==="tools"?"tool":"epi")?item.description:""} onChange={e=>setItem({...item,itemType:tab==="tools"?"tool":"epi",description:e.target.value})}/></label><label>Fornecedor<input value={item.supplier} onChange={e=>setItem({...item,supplier:e.target.value})}/></label>{tab==="epi"&&<label>CA<input value={item.ca} onChange={e=>setItem({...item,ca:e.target.value})}/></label>}</div>
  <button className="primary" onClick={()=>save({action:"saveItem",...item,itemType:tab==="tools"?"tool":"epi"})}>Salvar {tab==="epi"?"EPI":"ferramenta"}</button>
  <Table rows={items} cols={[["id","Código"],["description","Descrição"],["supplier","Fornecedor"],["ca","CA"],["usage_count","Fornecimentos"]]} edit={setItem} del={x=>save({action:"delete",entity:"item",id:x.id})}/>
  <section id="issue-form" className="bulk-issue-card">
   <div className="bulk-issue-heading"><div><small>FORNECIMENTO COLETIVO</small><h3>{tab==="epi"?"Entrega de EPIs":"Entrega de ferramentas"}</h3></div><span>{issue.contractIds.length} colaborador(es) · {issue.itemIds.length} item(ns)</span></div>
   <div className="form-grid issue-main-fields"><label>Data do fornecimento<input type="date" value={issue.issueDate} onChange={e=>setIssue({...issue,issueDate:e.target.value})}/></label><label>Quantidade por item<input type="number" min="0.01" step="0.01" value={issue.quantity} onChange={e=>setIssue({...issue,quantity:e.target.value})}/></label><label>Previsão de devolução/troca<input type="date" value={issue.returnDueDate} onChange={e=>setIssue({...issue,returnDueDate:e.target.value})}/></label><label className="wide">Condição e observações<input value={issue.notes} onChange={e=>setIssue({...issue,notes:e.target.value})}/></label></div>
   <div className="bulk-pickers">
    <div className="bulk-picker"><div className="bulk-picker-head"><b>Colaboradores</b><button type="button" onClick={()=>setIssue({...issue,contractIds:visibleWorkers.map((x:any)=>x.id)})}>Marcar todos</button><button type="button" onClick={()=>setIssue({...issue,contractIds:[]})}>Desmarcar</button></div><input placeholder="Filtrar por matrícula ou nome" value={workerFilter} onChange={e=>setWorkerFilter(e.target.value)}/><div className="bulk-check-list">{visibleWorkers.map((x:any)=><label key={x.id}><input type="checkbox" checked={issue.contractIds.map(String).includes(String(x.id))} onChange={()=>toggle("contractIds",x.id)}/><span><b>{x.registration_number?`MAT ${x.registration_number} · `:""}{x.name}</b><small>{x.role||"Sem função"}</small></span></label>)}</div></div>
    <div className="bulk-picker"><div className="bulk-picker-head"><b>{tab==="epi"?"EPIs":"Ferramentas"}</b><button type="button" onClick={()=>setIssue({...issue,itemIds:visibleItems.map((x:any)=>x.id)})}>Marcar todos</button><button type="button" onClick={()=>setIssue({...issue,itemIds:[]})}>Desmarcar</button></div><input placeholder={`Filtrar ${tab==="epi"?"EPI":"ferramenta"}`} value={itemFilter} onChange={e=>setItemFilter(e.target.value)}/><div className="bulk-check-list">{visibleItems.map((x:any)=><label key={x.id}><input type="checkbox" checked={issue.itemIds.map(String).includes(String(x.id))} onChange={()=>toggle("itemIds",x.id)}/><span><b>{x.description}</b><small>{x.ca?`CA ${x.ca}`:x.supplier||"Sem fornecedor"}</small></span></label>)}</div></div>
   </div>
   <label className="check-field"><input type="checkbox" checked={issue.acknowledged} onChange={e=>setIssue({...issue,acknowledged:e.target.checked})}/>Os colaboradores confirmaram o recebimento e a orientação de uso</label>
   <button className="primary" disabled={saving||!issue.contractIds.length||!issue.itemIds.length} onClick={()=>save({action:"issueItems",...issue}).then(ok=>ok&&setIssue({...issue,itemIds:[],contractIds:[]}))}>{saving?"Registrando…":`Registrar ${issue.contractIds.length*issue.itemIds.length} fornecimento(s)`}</button>
  </section>
  <section className="issue-history print-issue-history"><div className="bulk-issue-heading"><div><small>HISTÓRICO</small><h3>Fornecimentos registrados</h3></div><div><button type="button" className="secondary" onClick={()=>setShowIssueHistory(v=>!v)}>{showIssueHistory?"Ocultar":"Visualizar"}</button><button type="button" className="primary" onClick={printIssues}>Imprimir</button></div></div>{showIssueHistory&&<Table rows={issueRows.map((row:any)=>({...row,issue_date:String(row.issue_date||"").split("-").reverse().join("/"),quantity:row.quantity||"1"}))} cols={[["issue_date","Data"],["worker_name","Colaborador"],["item_description",tab==="epi"?"EPI":"Ferramenta"],["quantity","Quantidade"],["condition_notes","Observações"]]}/>}</section>
 </>}
 </section>
}
function CboSearchFields({value,setValue}:{value:any;setValue:(value:any)=>void}){
 const [results,setResults]=useState<Array<{code:string;description:string}>>([]),[status,setStatus]=useState("");
 const query=value.officialDescription||value.cboCode;
 useEffect(()=>{if(String(query).trim().length<2){setResults([]);return}const timer=setTimeout(async()=>{setStatus("Consultando a base oficial…");try{const r=await fetch(`/api/cbo?q=${encodeURIComponent(query)}`),b=await r.json();if(!r.ok)throw new Error(b.error);setResults(b.results||[]);setStatus((b.results||[]).length?"Selecione uma ocupação oficial.":"Nenhuma ocupação encontrada.")}catch(e){setStatus(e instanceof Error?e.message:"Falha na consulta oficial.")}},300);return()=>clearTimeout(timer)},[query]);
 const choose=(item:{code:string;description:string})=>{setValue({...value,cboCode:item.code,officialDescription:item.description,localDescription:value.localDescription||item.description});setResults([]);setStatus("CBO confirmado na base oficial do Ministério do Trabalho.")};
 return <div className="cbo-search"><div className="form-grid"><label>CBO<input placeholder="Digite o código" value={value.cboCode} onChange={e=>setValue({...value,cboCode:e.target.value})}/></label><label className="wide">Descrição oficial<input placeholder="Digite parte da função para pesquisar" value={value.officialDescription} onChange={e=>setValue({...value,officialDescription:e.target.value})}/></label><label className="wide">Descrição usada pela empresa<input value={value.localDescription} onChange={e=>setValue({...value,localDescription:e.target.value})}/></label></div>{status&&<small className="helper">{status}</small>}{results.length>0&&<div className="cbo-results">{results.map(item=><button type="button" key={`${item.code}-${item.description}`} onClick={()=>choose(item)}><b>{item.code}</b><span>{item.description}</span></button>)}</div>}</div>
}
function Table({rows,cols,edit,del}:{rows:any[];cols:[string,string][];edit?:(x:any)=>void;del?:(x:any)=>void}){return <div className="table-scroll"><table className="data-table"><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}{(edit||del)&&<th>Ações</th>}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}>{cols.map(c=><td key={c[0]}>{r[c[0]]??"—"}</td>)}{(edit||del)&&<td><div className="row-actions">{edit&&<button type="button" className="table-action" onClick={()=>edit(r)}>Editar</button>}{del&&<button type="button" className="table-action" onClick={()=>confirm("Excluir este registro? A exclusão será impedida se houver lançamentos associados.")&&del(r)}>Excluir</button>}</div></td>}</tr>)}</tbody></table></div>}
