"use client";
import { useEffect,useMemo,useState } from "react";
import "./hr.css";
type Tab="functions"|"references"|"adjustments"|"centers"|"epi"|"tools";
const today=()=>new Date().toISOString().slice(0,10), brl=(c:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format((c||0)/100);
export default function RegistrationsModule(){
 const [tab,setTab]=useState<Tab>("functions"),[data,setData]=useState<any>({functions:[],centers:[],references:[],items:[],issues:[],workers:[]}),[msg,setMsg]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState("");
 const [fn,setFn]=useState<any>({cboCode:"",officialDescription:"",localDescription:"",active:true}),[center,setCenter]=useState<any>({description:"",active:true}),[ref,setRef]=useState<any>({referenceType:"national",effectiveDate:today(),value:"",notes:""});
 const [item,setItem]=useState<any>({itemType:"epi",description:"",supplier:"",ca:"",active:true}),[issue,setIssue]=useState<any>({itemId:"",contractId:"",issueDate:today(),quantity:1,returnDueDate:"",notes:"",acknowledged:false}),[adj,setAdj]=useState<any>({functionIds:[],effectiveDate:today(),mode:"percentage",value:"",reason:"",updateProfiles:true});
 const load=async()=>{const r=await fetch(`/api/hr?fresh=${Date.now()}`,{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error||"Falha ao atualizar os cadastros.");setData(b);return b};
 useEffect(()=>{void load()},[]);
 const save=async(body:any)=>{setMsg("Salvando…");const r=await fetch("/api/hr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),b=await r.json();if(!r.ok){setMsg(b.error||"Não foi possível salvar.");return false}await load();setMsg(b.message||"Registro salvo e lista atualizada.");return true};
 const refs=useMemo(()=>data.references.filter((r:any)=>(!from||r.effective_date>=from)&&(!to||r.effective_date<=to)),[data,from,to]),items=data.items.filter((x:any)=>x.item_type===(tab==="tools"?"tool":"epi"));
 const tabs:[Tab,string][]=[["functions","Funções e CBO"],["references","Evolução salarial"],["adjustments","Reajuste salarial"],["centers","Centros de custo"],["epi","EPI"],["tools","Ferramentas"]];
 return <section className="module"><div className="module-hero"><span>▦</span><div><small>CADASTROS E HISTÓRICOS</small><h2>Cadastros</h2><p>Estrutura central para folha, segurança, patrimônio e análise gerencial.</p></div></div>
 {msg&&<div className="inline-notice">{msg}</div>}<div className="service-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==="functions"&&<><h3>Função oficial</h3><div className="form-grid"><label>CBO<input placeholder="Código oficial" value={fn.cboCode} onChange={e=>setFn({...fn,cboCode:e.target.value})}/></label><label className="wide">Descrição oficial<input placeholder="Pesquise/informe pelo código ou atividade" value={fn.officialDescription} onChange={e=>setFn({...fn,officialDescription:e.target.value})}/></label><label className="wide">Descrição associada usada pela empresa<input value={fn.localDescription} onChange={e=>setFn({...fn,localDescription:e.target.value})}/></label></div><button className="primary" onClick={()=>save({action:"saveFunction",...fn}).then(ok=>ok&&setFn({cboCode:"",officialDescription:"",localDescription:"",active:true}))}>Salvar função</button><Table rows={data.functions} cols={[["cbo_code","CBO"],["official_description","Descrição oficial"],["local_description","Descrição interna"],["usage_count","Vínculos"]]} edit={setFn} del={x=>save({action:"delete",entity:"function",id:x.id})}/></>}
 {tab==="references"&&<><div className="service-tabs"><button className={ref.referenceType==="national"?"active":""} onClick={()=>setRef({...ref,referenceType:"national"})}>Salário mínimo nacional</button><button className={ref.referenceType==="category"?"active":""} onClick={()=>setRef({...ref,referenceType:"category"})}>Salário da categoria</button></div><div className="form-grid"><label>Data do reajuste<input type="date" value={ref.effectiveDate} onChange={e=>setRef({...ref,effectiveDate:e.target.value})}/></label><label>Valor (R$)<input type="number" step=".01" value={ref.value} onChange={e=>setRef({...ref,value:e.target.value})}/></label><label className="wide">Observação<input value={ref.notes} onChange={e=>setRef({...ref,notes:e.target.value})}/></label></div><button className="primary" onClick={()=>save({action:"saveReference",...ref})}>Registrar evolução</button><div className="form-grid history-filter"><label>Data inicial<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Data final<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><Table rows={refs.map((r:any)=>({...r,value:brl(r.value_cents),type:r.reference_type==="national"?"Nacional":"Categoria"}))} cols={[["effective_date","Data"],["type","Referência"],["value","Valor"],["notes","Observação"]]}/></>}
 {tab==="adjustments"&&<><div className="form-grid"><label className="wide">Funções contempladas<select multiple value={adj.functionIds.map(String)} onChange={e=>setAdj({...adj,functionIds:Array.from(e.target.selectedOptions,o=>Number(o.value))})}>{data.functions.map((f:any)=><option key={f.id} value={f.id}>{f.cbo_code} · {f.local_description||f.official_description}</option>)}</select><small>Nenhuma seleção = todas as funções ativas.</small></label><label>Data do reajuste<input type="date" value={adj.effectiveDate} onChange={e=>setAdj({...adj,effectiveDate:e.target.value})}/></label><label>Forma<select value={adj.mode} onChange={e=>setAdj({...adj,mode:e.target.value})}><option value="percentage">Índice percentual</option><option value="value">Novo salário</option></select></label><label>{adj.mode==="percentage"?"Percentual (%)":"Novo salário (R$)"}<input type="number" step=".01" value={adj.value} onChange={e=>setAdj({...adj,value:e.target.value})}/></label><label className="wide">Motivo/observação<input value={adj.reason} onChange={e=>setAdj({...adj,reason:e.target.value})}/></label><label className="check-field"><input type="checkbox" checked={adj.updateProfiles} onChange={e=>setAdj({...adj,updateProfiles:e.target.checked})}/>Atualizar cadastro dos colaboradores após confirmação</label></div><button className="primary" onClick={()=>confirm("Confirma o reajuste e a atualização do histórico salarial?")&&save({action:"applyAdjustment",...adj})}>Visualizar e confirmar reajuste</button> <button className="danger" onClick={()=>confirm(`Desfazer reajustes de ${adj.effectiveDate}?`)&&save({action:"undoAdjustment",effectiveDate:adj.effectiveDate})}>Desfazer por data</button></>}
 {tab==="centers"&&<><div className="form-grid"><label className="wide">Descrição do centro de custo<input value={center.description} onChange={e=>setCenter({...center,description:e.target.value})}/></label></div><button className="primary" onClick={()=>save({action:"saveCenter",...center}).then(ok=>ok&&setCenter({description:"",active:true}))}>Salvar centro de custo</button><Table rows={data.centers} cols={[["description","Descrição"],["created_at","Criação"],["usage_count","Serviços vinculados"]]} edit={setCenter} del={x=>save({action:"delete",entity:"center",id:x.id})}/></>}
 {(tab==="epi"||tab==="tools")&&<><div className="service-tabs"><button className="active">Cadastro</button><button onClick={()=>document.getElementById("issue-form")?.scrollIntoView({behavior:"smooth"})}>Fornecimento</button></div><div className="form-grid"><label className="wide">Descrição<input value={item.itemType===(tab==="tools"?"tool":"epi")?item.description:""} onChange={e=>setItem({...item,itemType:tab==="tools"?"tool":"epi",description:e.target.value})}/></label><label>Fornecedor<input value={item.supplier} onChange={e=>setItem({...item,supplier:e.target.value})}/></label>{tab==="epi"&&<label>CA<input value={item.ca} onChange={e=>setItem({...item,ca:e.target.value})}/></label>}</div><button className="primary" onClick={()=>save({action:"saveItem",...item,itemType:tab==="tools"?"tool":"epi"})}>Salvar {tab==="epi"?"EPI":"ferramenta"}</button><Table rows={items} cols={[["id","Código"],["description","Descrição"],["supplier","Fornecedor"],["ca","CA"],["usage_count","Fornecimentos"]]} edit={setItem} del={x=>save({action:"delete",entity:"item",id:x.id})}/><h3 id="issue-form">Ficha de fornecimento</h3><div className="form-grid"><label>Item<select value={issue.itemId} onChange={e=>setIssue({...issue,itemId:e.target.value})}><option value="">Selecione…</option>{items.map((x:any)=><option key={x.id} value={x.id}>{x.description}</option>)}</select></label><label>Colaborador<select value={issue.contractId} onChange={e=>setIssue({...issue,contractId:e.target.value})}><option value="">Selecione…</option>{data.workers.map((x:any)=><option key={x.id} value={x.id}>{x.name} · {x.role||"sem função"}</option>)}</select></label><label>Data<input type="date" value={issue.issueDate} onChange={e=>setIssue({...issue,issueDate:e.target.value})}/></label><label>Quantidade<input value={issue.quantity} onChange={e=>setIssue({...issue,quantity:e.target.value})}/></label><label>Previsão de devolução/troca<input type="date" value={issue.returnDueDate} onChange={e=>setIssue({...issue,returnDueDate:e.target.value})}/></label><label className="wide">Condição e observações<input value={issue.notes} onChange={e=>setIssue({...issue,notes:e.target.value})}/></label><label className="check-field"><input type="checkbox" checked={issue.acknowledged} onChange={e=>setIssue({...issue,acknowledged:e.target.checked})}/>Colaborador confirmou recebimento e orientação de uso</label></div><button className="primary" onClick={()=>save({action:"issueItem",...issue})}>Registrar fornecimento</button></>}
 </section>
}
function Table({rows,cols,edit,del}:{rows:any[];cols:[string,string][];edit?:(x:any)=>void;del?:(x:any)=>void}){return <div className="table-scroll"><table className="data-table"><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}{(edit||del)&&<th/>}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}>{cols.map(c=><td key={c[0]}>{r[c[0]]??"—"}</td>)}{(edit||del)&&<td><div className="row-actions">{edit&&<button className="table-action" onClick={()=>edit(r)}>Editar</button>}{del&&<button className="table-action" onClick={()=>confirm("Excluir este registro?")&&del(r)}>Excluir</button>}</div></td>}</tr>)}</tbody></table></div>}
